### ISSUE TITLE
Give flexibility to the users by allowing them to specify remote configuration

### ISSUE THREAD

**Issue by satheeshravir** [prestodb/presto-admin#339] opened 2017-04-27 22:30 UTC
Grab some of the paths from the environment variables. It give flexibility to the users. For example constants.py can be modified as follows

`REMOTE_CONF_DIR = os.environ['PRESTO_REMOTE_CONF_DIR'] if 'PRESTO_REMOTE_CONF_DIR' in os.environ else '/etc/presto'`

**Comment by rschlussel** [comment] 2017-04-28 13:25
For variables that get set in Presto config files, I think the right way to do this would be to get the values directly from the config files.  e.g. look at remote_config_util.py to see how we do this for the getting the Presto log directories and the catalog directory.  Even for these, it looks like in some places in the code the constants get used instead of calling these functions, so those usages just need to be replaced with the appropriate function call.

**Comment by rschlussel** [comment] 2017-04-28 13:33
This is  a duplicate of https://github.com/prestodb/presto-admin/issues/229

**Closed by rschlussel** 2017-04-28 13:33 UTC

**Comment by satheeshravir** [comment] 2017-04-29 22:56
Thank you for the comment.
I will update the code to fetch values from config files. I will push the changes whenever I get time
