### ISSUE TITLE
Support for variables in configuration files

### ISSUE THREAD

**Issue by sogorkis** [prestodb/presto-admin#35] opened 2015-08-11 13:32 UTC
I need to add `-Djava.rmi.server.hostname=HOSTNAME` to coordinator and all workers `jvm.config` files. 

It would be useful to use variables (_hostname_, _ip_addr_, etc.) in configuration files.

**Comment by kokosing** [comment] 2017-03-08 21:27
closing as duplicate of #329

**Closed by kokosing** 2017-03-08 21:27 UTC
Labels: enhancement
